---
- name: Debian - Install apt-transport-https to support https APT downloads
  become: yes
  apt: name=apt-transport-https state=present
  when: use_repository

- name: Debian - Add filebeat repository key
  become: yes
  apt_key: url="{{ filebeat_apt_key }}" state=present
  when: use_repository and filebeat_apt_key

- name: Debian - Add filebeat repository
  become: yes
  apt_repository: repo={{ item.repo }} state={{ item.state}}
  with_items:
    - { repo: "{{ filebeat_apt_url }}", state: "present" }
  when: use_repository

- name: Debian - Install filebeat package from repository
  become: yes
  apt: name=filebeat{% if filebeat_version is defined and filebeat_version != "" %}={{ filebeat_version }}{% endif %} state=present force={{force_install}} allow_unauthenticated={{ 'no' if filebeat_apt_key else 'yes' }} cache_valid_time=86400
  when: use_repository
  register: debian_filebeat_install_from_repo
  notify: restart filebeat

- name: Debian - Download filebeat from url
  get_url: url={% if filebeat_custom_package_url is defined %}{{ filebeat_custom_package_url }}{% else %}{{ package_url }}-{{ filebeat_version }}-amd64.deb{% endif %} dest=/tmp/filebeat-{{ filebeat_version }}-amd64.deb validate_certs=no
  when: not use_repository

- name: Debian - Install filebeat package
  become: yes
  apt: deb=/tmp/{{package}}
  when: not use_repository
  register: filebeat_install_from_package
  notify: restart filebeat

- name: Debian - Configure the filebeat to start automatically during boot
  become: yes
  shell: update-rc.d filebeat defaults 95 10