---
- name: Reload systemd
  command: systemctl daemon-reload
  when: (ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>='))

- name: Restart kafka
  service: name=kafka enabled=yes state=restarted
