---
- name: Copy
  become: yes
  template: src=roles/update_configuration/templates/apm-server/apm-server.yml dest={{apm_server_conf_dir}}/apm-server.yml owner={{ apm_server_user }} group={{ apm_server_group }} mode={{apm_server_file_mask}} force=yes
  register: system_change
  notify: restart apm-server

- name: Copy fields.yml File
  become: yes
  template: src=roles/update_configuration/templates/apm-server/fields.yml dest={{apm_server_conf_dir}}/fields.yml owner={{ apm_server_user }} group={{ apm_server_group }} mode={{apm_server_file_mask}} force=yes
  register: system_change
  notify: restart apm-server

